[workspace]
members = [
    "komp",
    "kflatc",
    "kflat-lsp",
    "kf-core",
    "kf-parse",
    "kf-assemble",
    "kf-resolve",
    "kf-typecheck",
    "kf-mono",
    "kf-lower",
    "kf-codegen",
    "kf-interface",
    "kf-shared",
    "kf-driver",
    "kf-tool",
    "kf-integration",
    "../libs/core",
    "../libs/alloc",
    "../libs/std"
]
default-member = "komp"
